#!/bin/bash

sudo umount /dev/sda1
sudo umount /dev/sdb1
sudo umount /dev/sdc1
clear
sudo umount /home/pi/RAID0
sudo umount /home/pi/RAID5
clear
sudo mdadm -S /dev/md0
sudo mdadm -S /dev/md5
clear
sudo mdadm --zero-superblock /dev/sda1 /dev/sdc1 /dev/sdb1
clear
echo yes | sudo mdadm --create /dev/md5 --level=5 --raid-device=3 /dev/sda1 /dev/sdb1 /dev/sdc1
cat /proc/mdstat
clear
echo done | sudo mkfs -t ext4 /dev/md5
clear
sudo mount -o rw /dev/md5 /home/pi/RAID5
clear

echo ===========================================================
echo ===========================================================

